# Generated by Django 2.1.7 on 2019-03-22 11:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credentials',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
