# Generated by Django 2.1.7 on 2019-04-01 18:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_dir',
            field=models.CharField(default=core.models.get_random_seq, max_length=255),
        ),
    ]
