# Generated by Django 2.1.7 on 2019-04-01 19:48

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_temp_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chat')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='temp_dir',
            field=models.CharField(default=core.models.get_random_seq, max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('provider', 'uid')},
        ),
    ]
