# Generated by Django 2.1.7 on 2019-06-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190507_1813'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('uid', 'provider', 'owner')},
        ),
    ]
